---
- name: Converge 8.1
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    percona_mysql_version: '8.1'
    percona_mysql_root_password: SOMELONGTESTPASSWORD
  tasks:
  - name: Include andrelohmann.percona_mysql
    ansible.builtin.include_role:
      name: "andrelohmann.percona_mysql"
...
