---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: ubuntu_jammy
  image: ubuntu:22.04
  docker_extra_args:
  - --cap-add=SYS_ADMIN
  command: /sbin/init
  tmpfs:
  - /tmp
  - /run
  - /run/lock
  privileged: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - /var/lib/containerd
  cgroupns_mode: host
  pre_build_image: false
  dockerfile: Dockerfile.j2
- name: ubuntu_noble
  image: ubuntu:24.04
  docker_extra_args:
  - --cap-add=SYS_ADMIN
  command: /sbin/init
  tmpfs:
  - /tmp
  - /run
  - /run/lock
  privileged: true
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - /var/lib/containerd
  cgroupns_mode: host
  pre_build_image: false
  dockerfile: Dockerfile.j2
provisioner:
  name: ansible
verifier:
  name: ansible
...
