---

- name: Install percona key
  apt_key:
    keyserver: keys.gnupg.net
    id: 1C4CBDCDCD2EFD2A
    state: present

- name: Add Percona repository key
  apt_key:
    keyserver: keys.gnupg.net
    id: 9334A25F8507EFA5
    state: present

- name: Adding percona repository
  apt_repository:
    repo: "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state: present

- name: Adding percona source repository
  apt_repository:
    repo: "deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state: present

- name: Install percona database server
  apt:
    pkg: "{{ item }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - "percona-server-server-{{ percona_mysql_version }}"
  - "percona-server-client-{{ percona_mysql_version }}"
  - percona-toolkit
  - percona-xtrabackup
  - python-mysqldb

- name: Start mysql server
  service:
    name: mysql
    state: started

- name: get .my.cnf state
  stat:
    path: /root/.my.cnf
  register: _my_cnf

- name: Update MySQL root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ percona_mysql_root_password }}"
    login_user: root
    login_password: "{{ percona_mysql_root_password }}"
    check_implicit_admin: yes
  with_items:
  - "{{ ansible_hostname }}"
  - "127.0.0.1"
  - "::1"
  - "localhost"
  when: _my_cnf.stat.exists == False

- name: Copy .my.cnf file into the root home folder
  template:
    src: root.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  when: _my_cnf.stat.exists == False

- name: Ensure anonymous users are not in the database
  become: true
  become_user: root
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
  - "{{ ansible_hostname }}"
  - localhost

- name: remove test database
  mysql_db:
    name: test
    state: absent

- name: Create fnv1a_64
  shell: /usr/bin/mysql -e "CREATE FUNCTION fnv1a_64 RETURNS INTEGER SONAME 'libfnv1a_udf.so'" && touch /var/log/libfnv1a_udf.so.done creates=/var/log/libfnv1a_udf.so.done

- name: Create fnv_64
  shell: /usr/bin/mysql -e "CREATE FUNCTION fnv_64 RETURNS INTEGER SONAME 'libfnv_udf.so'" && touch /var/log/libfnv_udf.so.done creates=/var/log/libfnv_udf.so.done

- name: Create murmur_hash
  shell: /usr/bin/mysql -e "CREATE FUNCTION murmur_hash RETURNS INTEGER SONAME 'libmurmur_udf.so'" && touch /var/log/libmurmur_udf.so.done creates=/var/log/libmurmur_udf.so.done

...
