---

- name: Add Percona repository key
  apt_key:
    keyserver: keys.gnupg.net
    id: 8507EFA5
    state: present

- name: Adding percona repository
  apt_repository:
    repo: "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state: present

- name: Install percona database server
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - "percona-server-server-{{ percona_mysql_version }}"
    - "percona-server-client-{{ percona_mysql_version }}"
    - python3-mysqldb

...
