---
- hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    # percona_mysql_version: '8'
    percona_mysql_version: '8.1'
    percona_mysql_root_password: SOMELONGTESTPASSWORD

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-percona_mysql

...
