---
- hosts: all
  become: true
  become_method: sudo

  vars:
    # percona_mysql_version: '8'
    percona_mysql_version: '8.1'
    percona_mysql_root_password: SOMELONGTESTPASSWORD

  roles:
  - andrelohmann.root_colored_prompt
  - ansible-role-percona_mysql

...
