---
name: Test

on:
  push:
    branches:
    - "feature/*"
    - "fix/*"
    - "hotfix/*"
    - "release/*"
    - "major/*"
    - main

jobs:
  call-workflow:
    uses: ./.github/workflows/molecule.yml
    secrets: inherit
...
